name: Python CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the 'master' branch

jobs:
  test:
    runs-on: windows-latest  # Use the latest Ubuntu runner for the job
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Checkout the repository's code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from your requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run tests with pytest

    - name: Upload test results (optional)
      if: always()  # Ensure this step runs regardless of test success/failure
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: test-reports/*.xml  # Path to your JUnit test results (if you're generating them)
